version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app

hooks:
  BeforeInstall:
    - location: /app/scripts/cleanup.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /app/scripts/deploy_blue_green.sh
      timeout: 300
      runas: root
